(()=>{if(globalThis.__LOCAL_LEAD_URL_PANEL__)return;globalThis.__LOCAL_LEAD_URL_PANEL__=true;
const PANEL_UI_VERSION=1,DEFAULT_UI={panelSide:"right",panelOpen:true,panelForm:{target:"50",qwenModel:"qwen3.7-plus",region:"intl",icpUrl:""}};
const host=document.createElement("div");host.id="local-lead-url-lens";document.documentElement.append(host);const root=host.attachShadow({mode:"open"}),icon=chrome.runtime.getURL("icons/icon-128.png");
root.innerHTML=`<style>*{box-sizing:border-box}.launcher{position:fixed;right:16px;bottom:88px;z-index:2147483646;width:58px;height:58px;border:0;border-radius:14px;background:#fff url('${icon}') center/48px no-repeat;box-shadow:0 8px 28px #001f2660;cursor:grab}.panel{position:fixed;inset:0 0 0 auto;z-index:2147483647;width:min(440px,94vw);background:#f5faf8;border-left:1px solid #bed2cc;box-shadow:0 0 32px #001f2640;color:#102a2d;font:13px Inter,Arial,sans-serif;display:flex;flex-direction:column}.panel.left{left:0;right:auto;border-left:0;border-right:1px solid #bed2cc}.panel[hidden]{display:none}.head{display:flex;align-items:center;gap:10px;padding:12px 15px;background:linear-gradient(135deg,#063b40,#087e77);color:white}.head img{width:42px;height:42px;border-radius:9px}.head small{display:block;color:#b8ece6}.head button{margin-left:auto}.body{overflow:auto;padding:12px;display:grid;gap:10px}.card{background:white;border:1px solid #d7e3df;border-radius:12px;padding:12px}.row,.controls{display:grid;gap:7px}.row{grid-template-columns:1fr 1fr}.controls{grid-template-columns:repeat(3,1fr)}.filerow{display:grid;grid-template-columns:1fr auto;gap:6px;align-items:center}.keyrow{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:4px}.linkbtn{background:none;border:0;color:#087f78;min-height:auto;padding:2px 4px;font-size:11px}.ok{color:#0a7d33}.warn{color:#b8860b}.err{color:#c0392b}label{display:grid;gap:5px;margin:7px 0;font-weight:700;font-size:11px}input,select,button,textarea{font:inherit;border:1px solid #bed2cc;border-radius:8px;min-height:38px;padding:7px 9px;background:white;color:#102a2d}textarea{min-height:64px;resize:vertical}button{font-weight:800;cursor:pointer}.primary{background:#087f78;color:white;border-color:#087f78}.hidden{display:none!important}.status,.muted{color:#61736f;line-height:1.45}.muted{font-size:10px}.progress{height:7px;background:#e3ece8;border-radius:8px;overflow:hidden}.progress i{display:block;height:100%;width:0;background:#0aa096}.stats{display:grid;grid-template-columns:repeat(5,1fr);text-align:center;font-size:10px}.stats b{display:block;color:#087f78;font-size:17px;overflow:hidden;text-overflow:ellipsis}.stats small{display:block;font-size:10px}</style>
<button class="launcher" title="Local Lead URL Lens"></button><aside class="panel" hidden><div class="head"><img src="${icon}" alt=""><div><b>Local Lead URL Lens</b><small>Capture + local ICP scoring · CSV</small></div><button id="minimize">—</button></div><div class="body">
<section class="card"><p class="muted"><b>No backend.</b> Open a LinkedIn <b>People Search</b> or <b>Sales Navigator</b> results tab, set your ICP and OpenAI key, then capture + score locally and download a CSV.</p></section>
<section class="card"><label>Vault passphrase (entered each session)<div class="filerow"><input id="pass" type="password" placeholder="Enter passphrase…" autocomplete="off"><button id="unlock">Unlock</button></div><div class="keyrow"><small id="vaultStatus" class="muted">Checking…</small><span><button id="changePass" class="linkbtn hidden">Change</button> <button id="lock" class="linkbtn hidden">Lock</button></span></div><p class="muted">API keys are encrypted with this passphrase (PBKDF2 + AES-GCM); it is never stored. Enter it once per browser session.</p></label>
<label>OpenAI API key — embeddings (text-embedding-3-small, required)<div class="filerow"><input id="openaiKey" type="password" placeholder="Enter OpenAI key to set…" autocomplete="off"><button id="openaiSave">Save &amp; verify</button></div><div class="keyrow"><small id="openaiStatus" class="muted">Not set</small><button id="openaiClear" class="linkbtn hidden">Clear</button></div></label>
<label>Qwen API key — ICP prose compile + location normalization (optional)<div class="filerow"><input id="qwenKey" type="password" placeholder="Enter Qwen key to set…" autocomplete="off"><button id="qwenSave">Save &amp; verify</button></div><div class="keyrow"><small id="qwenStatus" class="muted">Not set</small><button id="qwenClear" class="linkbtn hidden">Clear</button></div></label>
<label>Qwen model<input id="qwenModel" placeholder="qwen3.7-plus"></label>
<label>DashScope region (Qwen)<select id="region"><option value="intl">International (dashscope-intl)</option><option value="cn">China (dashscope)</option></select></label></section>
<section class="card"><label>ICP definition (accepted job titles / keywords / locations)<textarea id="icpText" placeholder="Paste your ICP here (prose or JSON with job_titles / keywords / locations)…"></textarea></label><div class="filerow"><input id="icpUrl" placeholder="…or paste a raw .md / .json URL"><button id="icpPick">Choose file</button></div><input id="icpFile" type="file" accept=".md,.txt,.json,.yaml,.yml" class="hidden"><p id="icpStatus" class="muted">Paste text, choose a file, or set a URL.</p>
<label>New prospect target<input id="target" type="number" min="1" max="1000" value="50"></label>
<button id="start" class="primary">Capture &amp; score on this search</button><button id="download" class="hidden">Download CSV</button>
<p class="muted">Each prospect is scored 0–100 with the fixed contract <b>Job Title 65 + Job Section/Headline 20 + Location 15</b>, deterministic in code (the LLM never assigns the score). Exact title/keyword matches count 1.0 directly; otherwise OpenAI-embedding cosines are calibrated (≤0.35→0, ≥0.80→1). With a Qwen key, accepted titles/keywords are expanded once into strict synonym/translation variants, and borderline scores (40–70) get an advisory <b>Qwen Review</b> column that never changes the score. Private/empty cards and rows whose embeddings can't run are <b>NOT COMPUTED</b> with a Note. CSV columns: Full Name;Job Title;Job Section;Headline;Location;ICP Search Score;Job Title (65);Job Section/Headline (20);Location (15);Qwen Review;Note;LinkedIn Url.</p></section>
<section class="card"><div class="controls"><button id="pause">Pause</button><button id="resume">Resume</button><button id="cancel">Cancel</button></div><div class="progress"><i id="bar"></i></div><b id="count">0 / 0</b><p id="status" class="status">Ready.</p><div class="stats"><span><b id="s1">0</b><small id="l1">Discovered</small></span><span><b id="s2">0</b><small id="l2">Captured</small></span><span><b id="s3">0</b><small id="l3">Scored</small></span><span><b id="s4">0</b><small id="l4">Not comp.</small></span><span><b id="s5">0</b><small id="l5">Stage</small></span></div></section>
</div></aside>`;
const $=id=>root.getElementById(id),launcher=root.querySelector(".launcher"),panel=root.querySelector(".panel"),send=m=>chrome.runtime.sendMessage(m);
let dragging=false,moved=false,start,panelForm={...DEFAULT_UI.panelForm},icpFileText="";
function setOpen(open){panel.hidden=!open;launcher.hidden=open;chrome.storage.local.set({panelOpen:open,minimized:!open})}
async function saveForm(){panelForm={...panelForm,target:$("target").value,qwenModel:$("qwenModel").value,region:$("region").value,icpUrl:$("icpUrl").value};await chrome.storage.local.set({panelForm})}
function restoreForm(form={}){panelForm={...DEFAULT_UI.panelForm,...form};for(const id of ["target","qwenModel","region","icpUrl"])$(id).value=panelForm[id]||DEFAULT_UI.panelForm[id]||""}
function render(state={}){if(state.mode!=="local"){$("status").textContent=state.message||"Ready.";return}const done=Number(state.done||0),total=Number(state.target||0),results=state.results||[];const scored=Number(state.scored||results.filter(r=>Number.isFinite(Number(r.icp_score))).length),nc=Number(state.notComputed||(results.length-scored));$("count").textContent=`${done} / ${total}`;$("bar").style.width=`${total?Math.min(100,Math.round(done/total*100)):0}%`;$("status").textContent=state.message||"Ready.";$("s1").textContent=Number(state.discovered||0);$("s2").textContent=results.length;$("s3").textContent=scored;$("s4").textContent=nc;$("s5").textContent=String(state.stage||"READY").replaceAll("_"," ");$("start").disabled=Boolean(state.running);const dl=$("download");if(dl)dl.classList.toggle("hidden",!(results.length>0||state.stage==="DONE"||state.stage==="CANCELLED"))}
function renderKey(kind,meta){const set=meta&&meta.set,verified=meta&&meta.verified,statusEl=$(kind+"Status"),clearEl=$(kind+"Clear"),input=$(kind+"Key");if(set){statusEl.textContent=verified?"🔒 Configured & connection verified":"🔒 Configured (unverified — Save & verify again)";statusEl.className="muted "+(verified?"ok":"warn");clearEl.classList.remove("hidden");input.value="";input.placeholder="•••••••••• stored — enter a new key to replace"}else{statusEl.textContent="Not set";statusEl.className="muted";clearEl.classList.add("hidden");input.placeholder="Enter key to set…"}}
function renderVault(st){const unlocked=st&&st.unlocked,has=st&&st.hasPassphrase,s=$("vaultStatus");if(unlocked){s.textContent="🔓 Unlocked for this session";s.className="muted ok";$("lock").classList.remove("hidden");$("changePass").classList.remove("hidden");$("unlock").textContent="Unlock";$("pass").placeholder="Unlocked — leave blank"}else if(has){s.textContent="🔒 Locked — enter your passphrase and Unlock";s.className="muted warn";$("lock").classList.add("hidden");$("changePass").classList.add("hidden");$("unlock").textContent="Unlock";$("pass").placeholder="Enter passphrase…"}else{s.textContent="No passphrase yet — enter one and press Create";s.className="muted";$("lock").classList.add("hidden");$("changePass").classList.add("hidden");$("unlock").textContent="Create";$("pass").placeholder="Choose a passphrase (min 6 chars)…"}for(const id of ["openaiSave","qwenSave"])$(id).disabled=!unlocked}
async function refresh(){const r=await send({type:"GET_STATUS"});if(!r)return;renderVault(r);renderKey("openai",r.meta&&r.meta.openai);renderKey("qwen",r.meta&&r.meta.qwen);if(r.cfg){if(r.cfg.region)$("region").value=r.cfg.region;if(r.cfg.qwenModel)$("qwenModel").value=r.cfg.qwenModel}}
async function saveKey(kind){const input=$(kind+"Key"),statusEl=$(kind+"Status"),value=input.value.trim();if(!value){statusEl.textContent="Enter a key first.";statusEl.className="muted err";return}statusEl.textContent="Verifying connection…";statusEl.className="muted";const msg={type:"SET_KEY",kind,value};if(kind==="qwen"){msg.model=$("qwenModel").value.trim();msg.region=$("region").value}const r=await send(msg);input.value="";if(!r||!r.ok){statusEl.textContent=(r&&r.error)||"Could not save key.";statusEl.className="muted err";return}if(r.verified){statusEl.textContent="🔒 Configured & connection verified";statusEl.className="muted ok"}else{statusEl.textContent=`🔒 Stored, but verification failed: ${r.error||"unknown"}`;statusEl.className="muted warn"}$(kind+"Clear").classList.remove("hidden");input.placeholder="•••••••••• stored — enter a new key to replace"}
async function resolveSource(text,url,label){if(text&&text.trim())return text;const link=(url||"").trim();if(!link)return "";try{const r=await fetch(link);if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}catch(e){throw new Error(`Could not fetch ${label}: ${e.message}`)}}
// drag
launcher.addEventListener("pointerdown",e=>{dragging=true;moved=false;const r=launcher.getBoundingClientRect();start={x:e.clientX,y:e.clientY,left:r.left,top:r.top};launcher.setPointerCapture(e.pointerId)});
launcher.addEventListener("pointermove",e=>{if(!dragging)return;moved=moved||Math.abs(e.clientX-start.x)>4||Math.abs(e.clientY-start.y)>4;launcher.style.left=`${Math.max(4,Math.min(innerWidth-62,start.left+e.clientX-start.x))}px`;launcher.style.top=`${Math.max(4,Math.min(innerHeight-62,start.top+e.clientY-start.y))}px`;launcher.style.right=launcher.style.bottom="auto"});
launcher.addEventListener("pointerup",async e=>{if(!dragging)return;dragging=false;launcher.releasePointerCapture(e.pointerId);const r=launcher.getBoundingClientRect(),side=r.left<innerWidth/2?"left":"right";launcher.style.left=`${side==="left"?8:innerWidth-66}px`;panel.classList.toggle("left",side==="left");await chrome.storage.local.set({panelSide:side,panelPosition:r.top});if(!moved)setOpen(true)});
launcher.onclick=()=>{if(!moved)setOpen(true)};$("minimize").onclick=()=>setOpen(false);
for(const id of ["target","qwenModel","region","icpUrl"])$(id).addEventListener("change",saveForm);
$("icpPick").onclick=()=>$("icpFile").click();
$("icpFile").addEventListener("change",()=>{const file=$("icpFile").files&&$("icpFile").files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{icpFileText=String(reader.result||"");$("icpText").value=icpFileText;$("icpStatus").textContent=`Loaded ${file.name} (${(file.size/1024).toFixed(1)} KB)`};reader.onerror=()=>{$("icpStatus").textContent="Could not read file"};reader.readAsText(file)});
$("unlock").onclick=async()=>{const pass=$("pass").value;if(!pass){$("vaultStatus").textContent="Enter a passphrase.";$("vaultStatus").className="muted err";return}const st=await send({type:"GET_STATUS"});const type=st&&st.hasPassphrase?"UNLOCK_VAULT":"SET_PASSPHRASE";const r=await send({type,passphrase:pass});$("pass").value="";if(r&&r.ok){await refresh();$("status").textContent=type==="SET_PASSPHRASE"?"Vault created & unlocked.":"Vault unlocked for this session."}else{$("vaultStatus").textContent=(r&&r.error)||"Unlock failed.";$("vaultStatus").className="muted err"}};
$("changePass").onclick=async()=>{const pass=$("pass").value;if(!pass){$("vaultStatus").textContent="Type the NEW passphrase in the box, then Change.";$("vaultStatus").className="muted warn";return}const r=await send({type:"CHANGE_PASSPHRASE",passphrase:pass});$("pass").value="";if(r&&r.ok){await refresh();$("status").textContent="Passphrase changed; keys re-encrypted."}else{$("vaultStatus").textContent=(r&&r.error)||"Change failed.";$("vaultStatus").className="muted err"}};
$("lock").onclick=async()=>{await send({type:"LOCK_VAULT"});await refresh()};
$("openaiSave").onclick=()=>saveKey("openai");$("qwenSave").onclick=()=>saveKey("qwen");
$("openaiClear").onclick=async()=>{await send({type:"CLEAR_KEY",kind:"openai"});renderKey("openai",{set:false})};
$("qwenClear").onclick=async()=>{await send({type:"CLEAR_KEY",kind:"qwen"});renderKey("qwen",{set:false})};
$("start").onclick=async()=>{await saveForm();$("status").textContent="Loading ICP…";let icpText;try{icpText=await resolveSource($("icpText").value,$("icpUrl").value,"the ICP")}catch(e){return $("status").textContent=e.message}if(!icpText||!icpText.trim())return $("status").textContent="Provide an ICP (paste text, choose a file, or set a URL).";const target=Math.min(1000,Math.max(1,Number($("target").value)||50));const r=await send({type:"START_LOCAL",target,icpText,qwenModel:$("qwenModel").value.trim(),region:$("region").value});if(r&&r.error)$("status").textContent=r.error};
$("download").onclick=async()=>{const r=await send({type:"DOWNLOAD_CSV"});if(r&&r.error)$("status").textContent=r.error};
$("pause").onclick=()=>send({type:"PAUSE_OPERATION"});$("resume").onclick=()=>send({type:"RESUME_OPERATION"});$("cancel").onclick=()=>send({type:"CANCEL_OPERATION"});
chrome.runtime.onMessage.addListener(m=>{if(m.type==="TOGGLE_PANEL")setOpen(panel.hidden)});
chrome.storage.onChanged.addListener(changes=>changes.operationState&&render(changes.operationState.newValue||{}));
(async()=>{let state=await chrome.storage.local.get(["operationState","panelOpen","minimized","panelSide","panelPosition","panelForm","panelUiVersion"]);if(state.panelUiVersion!==PANEL_UI_VERSION){await chrome.storage.local.set({...DEFAULT_UI,panelUiVersion:PANEL_UI_VERSION});state={...state,...DEFAULT_UI,panelUiVersion:PANEL_UI_VERSION}}restoreForm(state.panelForm);panel.classList.toggle("left",state.panelSide==="left");if(state.panelPosition){launcher.style.top=`${state.panelPosition}px`;launcher.style.bottom="auto"}render(state.operationState||{});await refresh();setOpen(state.panelOpen===true)})();
})();
